FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye as builder
WORKDIR /app

COPY package.json ./
RUN npm install && npm cache clean --force

COPY . .

EXPOSE 3000

RUN npm run build
CMD ["npm", "run", "build"]

FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/dist/ .
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]